[package]
name = "daly"
version = "0.1.0"
authors = ["Jasper Schulz <jasper.b.schulz@gmail.com>"]

[dependencies]
maplit = "*"
kaktus = "0.1.2"
log = "0.3"
env_logger = "0.3"
frunk = "0.1.22"
frunk_core = "0.0.11"
boolinator = "2.4.0"
